[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.34"
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"

common = {path = "../common/"}
